<a href="https://colab.research.google.com/github/AadityaAdh/tf_gradient_tape/blob/main/gradient_tapee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gradient tape:
used to calculate gardient or derivative
syntax:

    with tf.gradienttape as tape:
      y=x**2


note:tape vanae ko chai yesari samjhini ki yellae chai record rakhxa
matlab mathi ko eg ma yo tape recording ma chai x ko y sanga ko relation sabbai record vai raa xa
    

In [ ]:
import tensorflow as tf

In [ ]:
x=tf.Variable([5.0])
with tf.GradientTape() as tape:
  y=x**2
dy_dx=tape.gradient(y,x)
print(dy_dx)

tf.Tensor([10.], shape=(1,), dtype=float32)


note:variable haru jati sabbai ko recording tape aafai lae rakhxa
but yedi kunai constant variable xa tyo chai use garnu parni xa differentiate garna vanae hamlae tape lai yesko ni record rakh hai vannu parxa or watch gaar vannu parxa using:

    tape.watch(your-constant variable)

In [ ]:
#constant lai watch gare na vanae k hunxa heram
x=tf.constant([5.0])
with tf.GradientTape() as tape:

  y=x**2
dy_dx=tape.gradient(y,x)
print(dy_dx)

None


 so watch na garae constant lai deerivative none aauxa obviously

In [ ]:
#now watching constant
x=tf.constant([5.0])
with tf.GradientTape() as tape:
  tape.watch(x)
  y=x**2
dy_dx=tape.gradient(y,x)
print(dy_dx)

tf.Tensor([10.], shape=(1,), dtype=float32)


# also expression pani tei with tape vitrai hunu parxa
natra ta tyo tape lae relationship record garnai paunna

In [ ]:
x=tf.Variable([5.0])
y=x**2
with tf.GradientTape() as tape:
  k=1

dy_dx=tape.gradient(y,x)
print(dy_dx)

None


#so tape vitra relationship ra watch garnu parni xa vanae tyo sabbai lekhni

# implementation : in deep learning

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import mse
from tensorflow.keras.optimizers import Adam

In [ ]:
def build_model():
  model=Sequential()
  model.add(Dense(1,input_shape=(2,)))
  model.add(Dense(12))
  model.add(Dense(1))
  model.compile(optimizer=Adam(learning_rate=0.1),loss=mse)
  return model

In [ ]:
model=build_model()

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 1)                 3         
                                                                 
 dense_8 (Dense)             (None, 12)                24        
                                                                 
 dense_9 (Dense)             (None, 1)                 13        
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# note:model ko relationship record garni ho vane .predict ma hunxa jasto bhujam

or simply model ko derivative wrt to each trainable variables garna ko lagi tape lae paila ta relation of output wrt to each parameters record garnu paryo
tyo record garauni equation chai model.predict ma hunxa vanae ko or simply model.predict chai tape vitra lekhnu parxa

aani variables lai watch chai .watch garai rakhnu pardaina as it is already variables ad already being watched by the tape

In [ ]:
inputs = tf.constant([[1.0, 2.0]])
targets = tf.constant([[2.0]])

In [ ]:


# note yo muni ko vanae ko aafai lae .fit garako jasto ho
#paila predict garna launi
#aani prediction aanusar loss
#aani derivative of loss wrt to each trainable paramenters
with tf.GradientTape() as tape:
    # Forward pass
    predictions = model(inputs)
    # Compute the loss
    my_loss = mse(targets, predictions)

# Compute gradients
gradients = tape.gradient(my_loss, model.trainable_variables)

In [ ]:
gradients

[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[16.479412],
        [32.958824]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([16.479412], dtype=float32)>,
 <tf.Tensor: shape=(1, 12), dtype=float32, numpy=
 array([[ 2.9560552 ,  2.2457519 , -3.106114  , -1.8236355 , -0.73855144,
          5.7419133 ,  1.972916  , -5.091543  ,  3.7493927 ,  0.43415612,
         -5.851799  , -3.7423937 ]], dtype=float32)>,
 <tf.Tensor: shape=(12,), dtype=float32, numpy=
 array([ 2.4747047 ,  1.880064  , -2.6003287 , -1.5266831 , -0.6182891 ,
         4.8069267 ,  1.6516554 , -4.2624598 ,  3.138859  ,  0.36346015,
        -4.898919  , -3.1329997 ], dtype=float32)>,
 <tf.Tensor: shape=(12, 1), dtype=float32, numpy=
 array([[ 4.382568  ],
        [ 2.3148072 ],
        [-5.6461487 ],
        [-4.5261545 ],
        [-0.26272354],
        [ 4.624916  ],
        [ 0.96463186],
        [-7.834239  ],
        [ 6.1084003 ],
        [-0.48243797],
        [-6.9884067 ],
        

In [ ]:
#aaba yo aako aako gardient ko value aauasar tyo trainable paramenters update garna ko lagi
optimizer=Adam(learning_rate=0.1)
optimizer.apply_gradients(zip(gradients,model.trainable_variables))
#note optimizers lae chai tyo gradient apply garxa

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

according to geeks for geeks:

What is tf.GradientTape in TensorFlow?
The tf.GradientTape class in TensorFlow is a Python tool used for calculating the gradients of a computation concerning certain inputs, typically tf.Variables. TensorFlow keeps track of relevant operations executed within the scope of a tf.GradientTape instance, recording them onto a “tape”. Upon calling the gradient() method on the tape, TensorFlow calculates the gradients of the recorded operations with respect to the specified inputs.

tf.GradientTape is a context manager that records the operations performed on tensors. Tensors are the basic data structures in TensorFlow, similar to arrays or matrices. A tensor can have any number of dimensions, shape, and data type. tf.GradientTape can track any tensor that is watched, either explicitly or implicitly.

Variables:

By default, tf.GradientTape will automatically watch any trainable variables accessed while the tape is active. Trainable variables are the variables that can be modified by the optimizer during training. They are usually created by tf.Variable with the argument trainable=True. Non-trainable variables, such as constants, are not watched by default. To watch a non-trainable tensor, we can use the tape.watch() method. To stop watching a tensor, we can use the tape.stop_recording() method.